### ISSUE TITLE
Add support for arrays of types.

### ISSUE THREAD

**Issue by vaikas-google** [kubernetes-incubator/apiserver-builder#119]
If in your resource definition you define a type:

type Foo struct {
   val1 string "`json...
   val2 string "`json...
}
and then use it say from the Spec

type SomeSpec struct {
   Foos []Foo
}

correct code on the unversioned type does not get generated. Work around is to use only basic array types and wrap the array of Foos as a struct and then use only basic arrays there.

**Comment by pwittrock** [comment]
Fixed in #121

**Comment by pwittrock** [comment]
Available in release [v0.1-alpha.11](https://github.com/kubernetes-incubator/apiserver-builder/releases/tag/v0.1-alpha.11)

**Comment by vaikas-google** [comment]
Fixed in #120
