### ISSUE TITLE
Support installation through apt-get on ubuntu

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder#128]

**Comment by metmajer** [comment]
Creating a .deb is one thing, but what are your plans with regards to distribution? Simplest solution would be to include the creation of .deb in our Makefile and append it as binary attachment to a GitHub release. What's your opinion, @pwittrock?

**Comment by metmajer** [comment]
@pwittrock I think it is useful and I'd suggest going with the simple solution. I just wasn't sure how the the kubernetes-incubator organization was set up and if they probably already have a deb repo or not. So, I'd suggest to integrate a build target in the project's Makefile that creates a .deb artefact in the project's `./bin` folder then.

**Comment by pwittrock** [comment]
@metmajer That sounds great to me.  We are lucky to have you on board.

**Comment by metmajer** [comment]
Resolved by #150. Feel free to close.

**Comment by pwittrock** [comment]
Built and uploaded: https://github.com/kubernetes-incubator/apiserver-builder/releases/tag/v0.1-alpha.17

**Comment by pwittrock** [comment]
@metmajer Do you have instructions for how one could use the .deb with `apt install apiserver-builder` `apt update apiserver-builder`?

**Comment by metmajer** [comment]
Here's how it works:

```
$ wget https://github.com/kubernetes-incubator/apiserver-builder/releases/download/v0.1-alpha.17/apiserver-builder-0.1-alpha.17-amd64.deb
$ apt install ./apiserver-builder-0.1-alpha.17-amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'apiserver-builder' instead of './apiserver-builder-0.1-alpha.17-amd64.deb'
The following NEW packages will be installed:
  apiserver-builder
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/41.4 MB of archives.
After this operation, 93.7 MB of additional disk space will be used.
Get:1 /home/apiserver-builder-0.1-alpha.17-amd64.deb apiserver-builder amd64 0.1-alpha.17 [41.4 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package apiserver-builder.
(Reading database ... 5099 files and directories currently installed.)
Preparing to unpack .../apiserver-builder-0.1-alpha.17-amd64.deb ...
Unpacking apiserver-builder (0.1-alpha.17) ...
Setting up apiserver-builder (0.1-alpha.17) ...
```

```
$ ls -la /usr/local/apiserver-builder/bin
total 91536
drwxrwxr-x 2 root root     4096 Sep 25 06:45 .
drwxrwxr-x 3 root root     4096 Sep 25 06:45 ..
-r-xr-xr-x 1 root root  7850864 Jan  1  1970 apiregister-gen
-r-xr-xr-x 1 root root  5757207 Jan  1  1970 apiserver-boot
-r-xr-xr-x 1 root root  7081889 Jan  1  1970 client-gen
-r-xr-xr-x 1 root root  6797345 Jan  1  1970 conversion-gen
-r-xr-xr-x 1 root root  6758779 Jan  1  1970 deepcopy-gen
-r-xr-xr-x 1 root root  6728969 Jan  1  1970 defaulter-gen
-r-xr-xr-x 1 root root 10004733 Jan  1  1970 gen-apidocs
-r-xr-xr-x 1 root root 16857263 Jan  1  1970 glide.tar.gz
-r-xr-xr-x 1 root root  6879175 Jan  1  1970 informer-gen
-r-xr-xr-x 1 root root  6684669 Jan  1  1970 lister-gen
-r-xr-xr-x 1 root root 12305818 Jan  1  1970 openapi-gen
```

An `apt update` would only update package information for those repos listed in `/etc/apt/sources.list`. An `apt upgrade` would then upgrade any previously installed packages if a newer version has been found. This only works if we set up our own apt repo.

For now, users would need to download and install a `.deb` via `apt install ./$release.deb`. This also works for upgrading to newer versions (the installation would simply be overwritten).
