### ISSUE TITLE
client-gen tag format has changed - will need to be updated when updating the vendored client-gen

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes-incubator/apiserver-builder#151]
Here is a failing log:
```
failed to run client-gen for unversioned APIs panic: +genclient=[true] is invalid, use //+genclient if you want to generate client or omit it when you want to disable generation
```

It looks `+genclient=[true]` should be replaced with `+genclient` instead now.

**Comment by pwittrock** [comment]
How did you get this error?

**Comment by yaxinlx** [comment]
It is reported by the latest client-gen: https://github.com/kubernetes/code-generator/tree/master/cmd
when running `apiserver-boot build generated` for one apiserver-boot generated project.

**Comment by pwittrock** [comment]
What is the version you downloaded?  The client-gen is vendored.  Are you currently experiencing this, or is it just to track needing to do this when we update the vendored code?

**Comment by yaxinlx** [comment]
Ah, I didn't notice the tools are built-in in this project.

**Comment by yaxinlx** [comment]
btw, I downloaded `apiserver-builder-v0.1-alpha.15-linux-amd64.tar.gz` from releases, but always get the error `apiserver-boot: cannot execute binary file: Exec format error`. I doubt the binary files are not correct.

`apiserver-builder-v0.1-alpha.14-linux-amd64.tar.gz` is ok.

**Comment by pwittrock** [comment]
@yaxinlx Thanks for noticing, it looks like there is an issue with the release script cross compiling. 

#153 Will look into this over the weekend.
