### ISSUE TITLE
.tar.gz archives created by apiserver-builder-release have wrong architecture

### ISSUE THREAD

**Issue by metmajer** [kubernetes-incubator/apiserver-builder#153]
I am working on the creation of .deb and .rpm packages for the apiserver-builder project in #150. To have the project built via `make build`, I am using the following approach in the Makefile:

```
.PHONY: build
build: clean ## Create release artefacts for darwin:amd64, linux:amd64 and windows:amd64. Requires etcd, glide, hg.
	go run ./cmd/apiserver-builder-release/main.go vendor --version $(VERSION)
	go run ./cmd/apiserver-builder-release/main.go build --version $(VERSION)
```

apiserver-builder-release uses `linux:amd64`, `darwin:amd64` and `windows:amd64` as default targets in [main.go](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-builder-release/main.go#L42), therefore the use of `--targets` is omitted here. Now, running `make build` creates the following build artefacts in `.`:

```
-rw-r--r--   1 metmajer  staff  42244411 Sep 22 22:04 apiserver-builder-0.1-alpha.14-darwin-amd64.tar.gz
-rw-r--r--   1 metmajer  staff  42244411 Sep 22 22:03 apiserver-builder-0.1-alpha.14-linux-amd64.tar.gz
-rw-r--r--   1 metmajer  staff  42244411 Sep 22 22:04 apiserver-builder-0.1-alpha.14-windows-amd64.tar.gz
```

As it turns out, all archives have the same size and are built for Darwin:

```
metmajer$ tar -xzf apiserver-builder-0.1-alpha.14-linux-amd64.tar.gz -C /tmp
metmajer$ file /tmp/bin/apiregister-gen
apiregister-gen: Mach-O 64-bit executable x86_64
```

Anything I'm doing wrong here?

**Comment by metmajer** [comment]
I have just verified that the same issue exists with the archives appended to the GitHub releases. It's a bug apiserver-builder-release.

**Comment by pwittrock** [comment]
@metmajer That is weird.  Someone else just noticed the same thing.

Must have introduced a regression at some point.  I suspect the issue is something in [this code](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-builder-release/main.go#L146).  If you feel comfortable, would you want to take a look?  Otherwise, I will try to take a look this weekend.

**Comment by pwittrock** [comment]
The glide issue is one I was worried about.  :(  Have been wanting to vendor glide into the project and invoke it directly instead of through exec.  #117

**Comment by metmajer** [comment]
Sure, let me have a look into it. I can't promise to have it fixed this weekend though.

**Comment by metmajer** [comment]
@pwittrock there's logic related to creating golang binaries in [apiserver-builder-release/main.go](https://github.com/kubernetes-incubator/apiserver-builder/blob/8307b995acc65028c42d88cba21c16840e843b85/cmd/apiserver-builder-release/main.go) which I do not understand well enough yet. I fear that a fix of mine could introduce unwanted side effects.

A quick look shows that [Build](https://github.com/kubernetes-incubator/apiserver-builder/blob/8307b995acc65028c42d88cba21c16840e843b85/cmd/apiserver-builder-release/main.go#L195) properly sets `GOOS=` and `GOARCH=` before invoking [RunCmd](https://github.com/kubernetes-incubator/apiserver-builder/blob/8307b995acc65028c42d88cba21c16840e843b85/cmd/apiserver-builder-release/main.go#L218). However, RunCmd then [unsets and populates cmd.Env](https://github.com/kubernetes-incubator/apiserver-builder/blob/8307b995acc65028c42d88cba21c16840e843b85/cmd/apiserver-builder-release/main.go#L172-L180), which effectively strips the previously injected `GOOS=` and `GOARCH=`. Hope this helps!

**Comment by pwittrock** [comment]
@metmajer Yup pretty sure that is it.  Verifying now.  #155

**Comment by pwittrock** [comment]
Uploading alpha .16 now.

**Comment by pwittrock** [comment]
File #156 to prevent this in the future.

**Comment by pwittrock** [comment]
[alpha.16](https://github.com/kubernetes-incubator/apiserver-builder/releases/tag/v0.1-alpha.16)

**Comment by admilazz** [comment]
I'm not sure if this bug is back or if it's a new bug, but v1.12.alpha.2 seems to have this problem as well.

**Comment by yue9944882** [comment]
> I'm not sure if this bug is back or if it's a new bug, but v1.12.alpha.2 seems to have this problem as well.

apologies, it's caused by a misconfiguration. release binaries refreshed.
