### ISSUE TITLE
Additional fields for apiserver.yam (imagePullSecrets and serviceAccount)

### ISSUE THREAD

**Issue by piotrjaromin** [kubernetes-incubator/apiserver-builder#178]
Hi, I have created pull request, below is description why I would like to have those changes: 

Currently I'm unable to generate and deploy api server with just one command, because I'm using secured private docker registry and k8s cluster with RBAC enabled.

What solves problem for me is editing apiserver.yaml and adding ImagePullSecrets and ServiceAccount to apiserver deployment. But doing this manually is cumbersome.

I would like to run it on one command like this (and this pull request enables it):
```
apiserver-boot run in-cluster --name group_name --namespace default --image private_repo/IMAGE --image-pull-secrets private_repo_secret --service-account service_account_with_rights
```

Currently I need to run:
```
    apiserver-boot build container --image $IMAGE_NAME
    docker push $IMAGE_NAME
    rm config/apiserver.yaml
    apiserver-boot build config --name remoteenvsgroup --namespace default --image $IMAGE_NAME
```
and then edit `apiserver.yaml` and run `kubectl apply`.

Also I have seen `controller-secret` flag but it is not used and I'm not sure if it place holder for `image-pull-secrets` functionality.

**Comment by pwittrock** [comment]
Merged the PR for this.  Closing the issue.  Thanks!

**Comment by pwittrock** [comment]
https://github.com/kubernetes-incubator/apiserver-builder/releases/tag/v0.1-alpha.19
