### ISSUE TITLE
blank fields in "openssl req" subj argument will fail the command for older openssl versions.

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes-incubator/apiserver-builder#186]
It looks order openssl versions will throw errors if some fields in the `subj` arguments are blank.

https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-boot/boot/build/build_resource_config.go#L182
https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-boot/boot/build/build_resource_config.go#L196

The issue, https://github.com/minio/minio/issues/3903, in another project suggests a solution.
I have verified `-subj /C=un/ST=st/L=l/O=o/OU=ou/CN=%s-certificate-authority` works.

**Comment by pwittrock** [comment]
@yaxinlx Cool.  Want to file a fix?

**Comment by yaxinlx** [comment]
submitted a pr.
