### ISSUE TITLE
wrong code generated for type field of type "k8s.io/apimachinery/pkg/apis/meta/v1".Time

### ISSUE THREAD

**Issue by yaxinlx** [kubernetes-incubator/apiserver-builder#196]
In the resource types of my project, there are some fields of type  `"k8s.io/apimachinery/pkg/apis/meta/v1".Time`.
However, in the generated code, the type becomes `"k8s.io/apimachinery/pkg/apis/meta".Time`.
This causes the generated code fails to compile.

**Comment by yaxinlx** [comment]
I must copy a `time.go` file from from `k8s.io/apimachinery/pkg/apis/meta/v1` to `k8s.io/apimachinery/pkg/apis/meta` folder to make it compile okay/

**Comment by pwittrock** [comment]
This should be fixed now.  Let me know if it isn't

**Comment by yaxinlx** [comment]
@pwittrock 
confirmed, it is fixed. Thanks!
