### ISSUE TITLE
Publish code generators as downloadable binary releases (.tar.gz)

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder#2]

**Comment by jimmidyson** [comment]
Should these binaries be published with Kubernetes releases?

**Comment by pwittrock** [comment]
Do you mean as part of them?  Or off of the release branches?  Or at the same time as releases?

I imagine we would want a set of releases that track the Kubernetes releases (GA), but also support periodic releases during the dev cycle (Beta).  We will want to publish the apiserver-builder code gen binaries more frequently.

**Comment by jimmidyson** [comment]
Seems a bit odd to publish releases of binaries not from the project where the source is... Perhaps these generators should be pulled out of core kube repo too?

**Comment by DirectXMan12** [comment]
IMO, it seems fairly reasonable to have the generators live here (and ideally eventually have the main Kubernetes pull them in instead).

**Comment by pwittrock** [comment]
As an interim solution I created:


https://github.com/kubernetes-incubator/apiserver-builder/releases/tag/v0.1-beta.1

**Comment by pwittrock** [comment]
Marking this as closed.  Can open another issue for moving the codegenerators into a single repo.  It could be this one, but the code generators are much more mature than the rest of the code in this repo, and this would need to move out of incubator for that.  WDYT of revisiting this in 3 months?

**Comment by DirectXMan12** [comment]
>  WDYT of revisiting this in 3 months?

Seems reasonable.
