### ISSUE TITLE
re-generate BUILD file for dependencies under vendor

### ISSUE THREAD

**Issue by eleanore0102** [kubernetes-incubator/apiserver-builder#201]
when initialize the project with `apiserver-boot init`, it will copy over the vendor directory from apiserver-boot to the initialized project. 

Notice that, the dependencies under vendor from apiserver-boot have BUILD file manually added (maybe not manually added? then can you please share how you generate them?)

that means, if I use dep ensure, it will wipe off the vendor directory, and re-download all the dependencies accordingly, then in this case, the BUILD files are gone, hence `apiserver-boot build executables --bazel --gazelle` does not work since the missing BUILD files for dependencies under vendor.

Any solutions for this use case?

**Comment by eleanore0102** [comment]
@pwittrock Any suggestions?

**Comment by pwittrock** [comment]
You can use gazelle to regenerate the BUILD files.  Alternatively, you can run init again to recopy over the deps.
