### ISSUE TITLE
Replace Glide with Dep when running init

### ISSUE THREAD

**Issue by peterj** [kubernetes-incubator/apiserver-builder#203]
Are there any plans to replace the `glide.yaml` creation [here](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/cmd/apiserver-boot/boot/init_repo/glide.go) with `Gopkg.toml` creation? Or perhaps add support for it if not replacing it?

**Comment by DirectXMan12** [comment]
replacing is probably unlike unless other parts of Kubernetes move to `dep` (I suspect they might eventually, but that might be a while out).  Support for `dep` in addition to `glide` is probably more acceptable at the moment, although I'll defer to @pwittrock for more guidance.

**Comment by pwittrock** [comment]
In the default case it doesn't even use glide.  It just copies the deps over from a directory.  The right solution here is probably for Kubernetes to come up with a way of exporting all of its transitive dependencies in a way that makes them easy to get.
