### ISSUE TITLE
dependents are not deleted when Owner object is delete

### ISSUE THREAD

**Issue by DuoyueBa** [kubernetes-incubator/apiserver-builder#204]
I created two kinds of resource: Api and ApiDescription, and ApiDescription depends on Api. My requirement is that ApiDescription is deleted when related Api is deleted. I add OwnerReference configuration in ApiDescription to refer to Api.

The following is ApiDescription yaml file:
apiVersion: aura.oracledx.com/v1alpha1
kind: ApiDescription
metadata:
  name: api-example-v1.1.0
  labels:
    api.oracledx.com/api: api-example-v1 # required
  ownerReferences:
  - apiVersion: aura.oracledx.com/v1alpha1
    controller: true
    blockOwnerDeletion: true
    kind: Api
    name: api-example-v1
    uid: 13872da4-ec3b-11e7-b622-80e6501e8e7e
spec:
  format: application/openapi+json

And Api is:
kubectl --kubeconfig kubeconfig get api -o json
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "aura.oracledx.com/v1alpha1",
            "kind": "Api",
            "metadata": {
                "creationTimestamp": "2017-12-29T01:53:33Z",
                "generation": 1,
                "labels": {
                    "api.oracledx.com/binding-name": "some-service"
                },
                "name": "api-example-v1",
                "namespace": "default",
                "resourceVersion": "53",
                "selfLink": "/apis/aura.oracledx.com/v1alpha1/namespaces/default/apis/api-example-v1",
                "uid": "13872da4-ec3b-11e7-b622-80e6501e8e7e"
            },
            "spec": {},

After I deleted Api, the ApiDescription is not deleted at same time.
kubectl --kubeconfig kubeconfig delete api api-example-v1 --cascade=true
api "api-example-v1" deleted

Could you help to check why ApiDescription is not deleted at same time? Thank you!

**Comment by pwittrock** [comment]
Are you running Kubernetes 1.9.0 or higher?

**Comment by pwittrock** [comment]
This was a Kubernetes issue in 1.8
