### ISSUE TITLE
[Question] How to use apiserver builder with custom auth

### ISSUE THREAD

**Issue by alok87** [kubernetes-incubator/apiserver-builder#207]
Want to use this to generate a standalone apiserver with custom auth. How to do that?
Where to make changes in code to do that...

**Comment by WIZARD-CXY** [comment]
You may start by this doc https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md

**Comment by alok87** [comment]
@WIZARD-CXY I have to write my own authorizer, authenticator and it is not going to be aggregated with kubernetes api server. I think this will require code change.  Not sure how the above doc will help in this case

**Comment by WIZARD-CXY** [comment]
ok then too fancy

**Comment by DirectXMan12** [comment]
The custom API servers built by this tool are mainly intended to be aggregated API servers that authenticate and authorize against a main Kubernetes API server.  That being said, it should be possible to enable a webhook authorizer and authenticator via the normal flags (IIRC), assuming you can implement your custom auth as a webhook.
