### ISSUE TITLE
Make apiserver-builder a purely development time tool

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-incubator/apiserver-builder#215]
I am trying to learn how to build an EAS. I am trying to understand the differences/similarities between sample-apiserver and apiserver-builder project. I like the apisever-builder approach as it makes the whole process easier to understand and follow. Currently the generated apiserver by apiserver-builder depends on some `helper` code from this project. Can the apiserver-boot be modified such that these `helpers` are actually added in the generated code so that generated apiserver has only dependencies on `k8s.io/..` packages? One key benefit will be that one can easily upgrade their client-go version without having this project to upgrade.

**Comment by pwittrock** [comment]
I'd rather upstream the libraries than have them generated.

**Comment by tamalsaha** [comment]
That sounds even better. I found the QueueWorker and Default** implementations for interfaces useful.
