### ISSUE TITLE
apiregister-gen not respects strategy tag

### ISSUE THREAD

**Issue by furykerry** [kubernetes-incubator/apiserver-builder#220]
Version: version.Version{ApiserverBuilderVersion:"v1.8-alpha.27.1", KubernetesVendor:"1.8.1", GitCommit:"c99ca7ebe533a7318338f3047edb498bb797d85e", BuildDate:"2018-01-22-08:00:51", GoOs:"darwin", GoArch:"amd64"}

apiregister-gen does not respect the strategy tag as in follows:
// +resource:path=Myresource,strategy=Mystrategy

APITemplate in the versioned_generator and unversioned_generator all use the following snipplet 

//
// {{.Kind}} Functions and Structs
//
// +k8s:deepcopy-gen=false
type {{.Kind}}Strategy struct {
	builders.DefaultStorageStrategy
}

so the generated stragtegy struct is always {{.Kind}}Strategy regardless the strategy tag setting

**Comment by pwittrock** [comment]
@furykerry Nice catch.  We should probably just delete that tag.  I think this it is very useful.
