### ISSUE TITLE
Use strategy tag when generating code

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder#221]

**Comment by pwittrock** [comment]
Address #220

**Comment by furykerry** [comment]
I prefer to modify the api template in unversioned_generator.go and versioned_generator.go. The following patch works for our cases, and I will submit my patch after some more tests

` // +k8s:deepcopy-gen=false
-type {{.Kind}}Strategy struct {
+type {{ $api.Strategy }} struct {
        builders.DefaultStorageStrategy
 }

 // +k8s:deepcopy-gen=false
-type {{$api.Kind}}StatusStrategy struct {
+type {{ $api.StatusStrategy }} struct {
        builders.DefaultStatusStorageStrategy
 }`

**Comment by pwittrock** [comment]
SGTM!
