### ISSUE TITLE
The field `priority` does not exist in `apiregistration.k8s.io/v1beta`

### ISSUE THREAD

**Issue by magicsong** [kubernetes-incubator/apiserver-builder#274]
when use kubectl apply -f config/apiserver.yaml, it throws following error:
```
error: error validating "config/apiserver.yaml": error validating data: ValidationError(APIService.spec): unknown field "priority" in io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.APIServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
Can i open a pr to remove this field?

**Comment by yue9944882** [comment]
at the first blush, it looks like a versioning mismatch between ur `kubectl` and the apiserver. whats the version of them?

**Comment by yue9944882** [comment]
SGTM. `priority` is replaced after [https://github.com/kubernetes/kubernetes/pull/46800](https://github.com/kubernetes/kubernetes/pull/46800). @magicsong is always welcome! thx!

btw, bump that apiversion to `v1` together in ur pull please 👍🏻
