### ISSUE TITLE
openapi-gen don't walk through subdirs

### ISSUE THREAD

**Issue by magicsong** [kubernetes-incubator/apiserver-builder#278]
i have a package in `v1alpha1`(under apis), and I add `// +k8s:openapi-gen=true` to in front of its package name. And `ApiServer` report following error.
```
unable to get openapi schema for devops.kubesphere.io/v1alpha1, Kind=XXX:
cannot find model definition for github.com/magicsong/apiserver/pkg/apis/devops/v1alpha1/api.Config. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again]
```
And I have to manually run following command each time: (Add a `/...` to original args)  
```
openapi-gen --input-dirs github.com/magicsong/apiserver/pkg/apis/devops/v1alpha1/...

##The orginal is 
## openapi-gen --input-dirs github.com/magicsong/apiserver/pkg/apis/devops/v1alpha1
```
Btw, i think this tool is more useful than CRD, why there is nobody to maintain this repo? Right now, this tool is hard to use (No detailed doc and some anti-devops bug)

**Comment by yue9944882** [comment]
> ~github.com/magicsong/apiserver/pkg/apis/devops/v1alpha1/api.Config~
> github.com/magicsong/apiserver/pkg/apis/devops/v1alpha1.Config

rule of thumb, normally we don't define models under subpackges and also what we do in k/k

>  i think this tool is more useful than CRD

thx so much for ur support! this project is still running towards graduation so any feedback (bug report/pulls/re's) will be super welcome and we are always ready to help. 

> why there is nobody to maintain this repo

nah huh, we are actually running this repo, hopefully will share more maintainer bandwidth from k/k in future. if necessary, we will be inviting guys to collaborate the pull. also, please free feel to contact us directly via slack.

**Comment by magicsong** [comment]
@yue9944882 glad to hear that! Thx for your reply, I will move the model out of subdir

**Comment by magicsong** [comment]
i try to import a package in apis definitions, it complains again.

**Comment by yue9944882** [comment]
by any chance, if you could show us ur code to reproduce the problem? a link to ur code/gist would be fine

**Comment by magicsong** [comment]
closed. I found a way to solve this
