### ISSUE TITLE
apiserver-boot build docs failed if using external etcd

### ISSUE THREAD

**Issue by magicsong** [kubernetes-incubator/apiserver-builder#280]
I use external etcd when debug in local. It can be done by  `apiserver-boot run local --run=apiserver --run=controller-manager --etcd "http://192.168.98.8:2379" --generate=false --build=false`
However i can't run `build docs` because etcd-server is hard-coded to "localhost:2379" in source.

**Comment by yue9944882** [comment]
hi @magicsong building docs doesn't matter which etcd you are referencing it's just a required option to launch the server. any use case for referencing external etcd i missed?

**Comment by magicsong** [comment]
@yue9944882 docs are generated by communicate with apiserver. The url is like `https://apiserver:9443/openapi`. So the etcd must be launched.

**Comment by yue9944882** [comment]
>  building docs doesn't matter which etcd you are referencing

@magicsong that apiserver doesn't read/write anything from that etcd. does that make sense?

**Comment by magicsong** [comment]
@yue9944882 If I understand correctly, apiserver is the only component that communicates with etcd. Apiserver must have a storage. You can check this code  <https://github.com/kubernetes-incubator/apiserver-builder/blob/c3c081711723ad2a0b009417153d00d5efd2c2c3/pkg/cmd/server/start.go#L84>

**Comment by magicsong** [comment]
@yue9944882 I think  `apiserver-boot build doc` does the following things:
1. run an `apiserver --print-openapi` to generate swagger.json ( it will clean up after command termination) 
2. use `gen-openapi` to generate "true" docs (which will stay on disk)
3. run a container to browser docs. (this container need swagger.json)
4. Always, cleanup.

So, I don't think apiserver is not neccessary.

**Comment by yue9944882** [comment]
> However, apiserver cannot run without etcd right now even it doesn't actually do some real stuffs to etcd.

to clarify, am not suggesting you to run apiserver w/o etcd option, but to run this w/ a local etcd as `localhost:2379`

**Comment by magicsong** [comment]
You should not ask user to run etcd locally or make other assumption. My laptop has poor performance and cannot run etcd or docker (In actual, I don't have to because I have some VMs). As Cloud Native project, etcd and apiserver should be loose coupling. Hard-code is ugly. If you insist on asking people to run etcd locally, you also should change codes in `apiserver-boot run local`, because that mode support external etcd.

**Comment by yue9944882** [comment]
i'm in favor of #272, to prune that etcd options when printing doc from an upstream fix. we have to be careful about adding falgs.

**Comment by magicsong** [comment]
@yue9944882 I'm careful enough( you should review the code to see what is changed). Also there is no plan for k8s to run apiserver without etcd(If have, pls  let me know). You prefer using hard-code instead of making it configurable. You cannot afford a feasible way but wait forever.

**Comment by yue9944882** [comment]
> there is no plan for k8s to run apiserver without etcd. (If have, pls let me know).

no, i'm planning that. also, attemption at [etcdproxy-controller](https://github.com/xmudrii/etcdproxy-controller). feel free to bump that topic at our sig-api-machinery meetings 🙂

**Comment by magicsong** [comment]
sounds great.  I'm happy to wait but right now i have to work on my fork.  This repo has so many TODO things(1. doc 2. shortNames 3. admission controller 4 Server side prints) which is more important than this issue (and this issue did have a workaround here #281 which is at least working well) , Without these features, using this tool to build AA is harder and more expensive even less flexible than CRD. This is not what AA suppose to be. Pls focus on these features.
