### ISSUE TITLE
Support running in aggregated mode using `apiserver-boot run --aggregated`

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-incubator/apiserver-builder#44]

**Comment by MHBauer** [comment]
@pwittrock does this PR look like it has potential to partially migrate here? If not, maybe we can talk soon to discuss getting aggregation "built-in" to this builder. 
https://github.com/kubernetes-incubator/service-catalog/pull/895

**Comment by pwittrock** [comment]
Yeah it does.  Looks like there is already a PR for it?

**Comment by pwittrock** [comment]
Looks like we have both the command `apiserver-boot run in-cluster` and the guide explaining the details now.
