### ISSUE TITLE
support custom registry

### ISSUE THREAD

**Issue by xiang90** [kubernetes-incubator/apiserver-builder#6]
It seems that there is no way to provide custom registry. We current use generic registry by default.

can it be customized? probably we should provide a doc to show how to do it.

**Comment by pwittrock** [comment]
can you explain more about this usecase?

**Comment by xiang90** [comment]
this is already addressed.

**Comment by xiang90** [comment]
my use case is to bypass the standard kuberentes storage layer, which is used by the default registry. i want to use my customized storage API and its implementation.

**Comment by pwittrock** [comment]
@xiang90 awesome, was wondering if that is what you were referring to
