### ISSUE TITLE
Imported package "pkg/apis/apps/install" is not found

### ISSUE THREAD

**Issue by ibazhitov** [kubernetes-incubator/apiserver-builder#62]
The generated code references an inexisting package "pkg/apis/apps/install".
Reproduced with v0.1-beta.11, but the same holds for master.

$ apiserver-boot init --domain example.com
$ apiserver-boot create-resource --domain example.com --group apps --version v1 --kind Application
$ apiserver-boot generate
$ apiserver-boot build
$ go test ./pkg/...
pkg/client/clientset_generated/internalclientset/scheme/register.go:5:2: cannot find package "github.com/ibazhitov/xxx/pkg/apis/apps/install" in any of:
	/go/src/github.com/ibazhitov/xxx/vendor/github.com/ibazhitov/xxx/pkg/apis/apps/install (vendor tree)
	/usr/lib/go-1.8/src/github.com/ibazhitov/xxx/pkg/apis/apps/install (from $GOROOT)
	/home/clm/wrk/go/src/github.com/ibazhitov/xxx/pkg/apis/apps/install (from $GOPATH)

**Comment by pwittrock** [comment]
Interesting.  I am not sure why the generated code references that.  Does `go test ./pkg/apis/...` work for you?

**Comment by ibazhitov** [comment]
> Does go test ./pkg/apis/... work for you?

Yes, all tests are working:

`
$ go test ./pkg/apis/...
?   	github.com/ibazhitov/xxx/pkg/apis	[no test files]
?   	github.com/ibazhitov/xxx/pkg/apis/apps	[no test files]
ok  	github.com/ibazhitov/xxx/pkg/apis/apps/v1	1.358s
$ go test ./pkg/controller/...
?   	github.com/ibazhitov/xxx/pkg/controller	[no test files]
ok  	github.com/ibazhitov/xxx/pkg/controller/application	1.310s
?   	github.com/ibazhitov/xxx/pkg/controller/sharedinformers	[no test files]
`
Meanwhile, I've found another problem with the missing 'install' package:
`
$ glide up
...
[ERROR]	Error scanning github.com/ibazhitov/xxx/pkg/apis/apps/install: open /go/src/github.com/ibazhitov/xxx/pkg/apis/apps/install: no such file or directory
...
`

**Comment by pwittrock** [comment]
Fixed this issue in the latest release, but still have some other compilation failures with the generated fakes...

**Comment by pwittrock** [comment]
Still working on this...
