### ISSUE TITLE
example in docs/ is outdated

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes-incubator/apiserver-builder#8]
This doc is oudated: https://github.com/kubernetes-incubator/apiserver-builder/tree/master/docs
- The example directory is outdated. We should point it into the example/ here.
- "Generate code" could be replaced by making use of the makefile under example/

Further improvements:
- It requires "minikube", which isn't necessary. Ideally we can make it in front of an etcd server.

**Comment by xiang90** [comment]
@hongchaodeng the minikube is for auth delegation. it is not really required to start a minimal apiserver. all you need is to

```
./etcd
./apiserver --delegated-auth=false --etcd-servers=http://127.0.0.0.1:2379 --secure-port=9443
```

**Comment by pwittrock** [comment]
@hongchaodeng none of this is required anymore and all of that logic is encapsulated in `apiserver-boot`.  Will update the docs and then close this issue.  Should be much easier.

**Comment by pwittrock** [comment]
@hongchaodeng Updated the docs to include the newest hotness.  Should be much simpler to get started now.  Next step will be simplifying starting a local server with or without delegated auth and automatically updating the .kube/config.
